### ISSUE TITLE
Setting up VIrtualBox and Vagrant using Mining the-Social-Web-2nd-Edition

### ISSUE THREAD

**Issue by Sarita9876** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#138]
I installed Vagrant and VirtaulBox. When I first run the Vagrant command within the CMD window In Windows 7 it never automatically installed the Precise64. I had to manually install it. How Do I connect the Mining-the-Social-Web-2nd-Edition.zip within the command window in Windows 7?

**Comment by james-roeschlein** [comment]
Hi , I am getting an error when I run the clone from git:
***********************************************************************************************************
$ git clone git@github.com:ptwobrussel/Mining-the-Social-Web-2nd-Edition.git
Cloning into 'Mining-the-Social-Web-2nd-Edition'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

*****************************************************************************************************************

Not sure if something has changed since I purchased the book?

**Comment by james-roeschlein** [comment]
I am new to this and sort of confused...Thanks.

**Comment by ptwobrussell** [comment]
Looks like you have a typo in the name of the repo. You are missing an l in ptwobrussell  

---Sent from Boxer | http://getboxer.com

On January 14, 2015 at 11:07:46 PM CST, james-roeschlein <notifications@github.com> wrote:I am new to this and sort of confused...Thanks.  —Reply to this email directly or view it on GitHub.

**Comment by james-roeschlein** [comment]
Thanks for the quick reply. I also tried it as I was missing the l but got the same reply?

roeschle@NEWXIS5L57 /c/WINDOWS/system32
$ git clone git@github.com:ptwobrussell/Mining-the-Social-Web-2nd-Edition.git
Cloning into 'Mining-the-Social-Web-2nd-Edition'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

roeschle@NEWXIS5L57 /c/WINDOWS/system32
$


Do I have to log in to github or authenticate somehow?

Jim
--------------------------------------------
On Thu, 1/15/15, Matthew A. Russell <notifications@github.com> wrote:

 Subject: Re: [Mining-the-Social-Web-2nd-Edition] Setting up VIrtualBox and Vagrant using Mining the-Social-Web-2nd-Edition (#138)
 To: "ptwobrussell/Mining-the-Social-Web-2nd-Edition" <Mining-the-Social-Web-2nd-Edition@noreply.github.com>
 Cc: "james-roeschlein" <james_roeschlein@yahoo.com>
 Date: Thursday, January 15, 2015, 6:57 AM
 
 
 
 
 
 
 
 This message is eligible for Automatic Cleanup!
 (notifications@github.com) 
 Add cleanup
 rule
  | More info

**Comment by ptwobrussell** [comment]
If you aren't already a GitHub user, you'll need to use the SSH-based clone
URL vs the git-based on that's available from the project page in the right
margin

https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition.git

**Comment by jmwoloso** [comment]
Hello!

When I have VirtualBox open during "vagrant up" I get an error from VirtualBox that says: "The instruction at 0xd67e8342 referenced memory at 0x00000021. The memory could not be read."

I'm pretty sure VirtualBox is configured fine because I'm doing a Udacity course on Hadoop which uses a VirtualBox instance and it runs just fine.

Here is the command line output from running "vagrant up":

(Canopy 64bit) c:\Code\oreilly\Mining-the-Social-Web-2nd-Edition>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'precise64' could not be found. Attempting to find and install.
..
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'precise64' (v0) for provider: virtualbox
    default: Downloading: http://files.vagrantup.com/precise64.box
    default: Progress: 100% (Rate: 367k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'precise64' (v0) for 'virtualbox'!
==> default: Importing base box 'precise64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: Mining-the-Social-Web-2nd-Edition_defau
lt_1434645153637_340
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8888 => 8888 (adapter 1)
    default: 5000 => 5000 (adapter 1)
    default: 27017 => 27017 (adapter 1)
    default: 27018 => 27018 (adapter 1)
    default: 27019 => 27019 (adapter 1)
    default: 28017 => 28017 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
