### ISSUE TITLE
Example 6.2 : cannot build the mbox file correctly

### ISSUE THREAD

**Issue by alafanechere** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#219]
I successfully ran the script to download and extract enron data (it returns the last prints : Decompression complete - Data is ready').
My problem is when I run the example 6.2 the scripts creates the mbox file, but the file is empty. I tried to open it with Apple Mail, which says it's empty. And when I try to run the next example the json file created is also empty. Do you have an idea why it happens ?
I got no error from both scripts...

**Comment by jlm2239** [comment]
Hi,
I am trying to take the Enron data and convert to a json file so that I can run another program that I have working that uses kmeans to cluster the emails.   I tried the code from 6.2 but I am getting the error: "unknown string format" for  _date=asctime(parse(_date).timetuple()).  I tried print _date and I get the entire message (so maybe re.search is not working?).   Any suggestions?  The mbox is created but is empty too.
