### ISSUE TITLE
Cant have Chef to successfully finish installing packages.

### ISSUE THREAD

**Issue by PaulDepraz** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#245]
Hi, I followed the instructions to clone your repo and run the vagrant vm. As it started Chef scripts ran and couldnt find python at /bin/ṕython. Then I sshed into the vm and created an softlink for it in that folder. Afterwards it stopped (as it seems) at trying to install Numpy. Could you please help me? I bumped the console output over here (https://drive.google.com/file/d/0BxkBT1UfVsGLVFh1NXp0RmhnZTQ/view?usp=sharing) so you or anyone could check. Im working at Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.63-2+deb7u1 and have the latest vagrant version intalled.

**Comment by ejovi** [comment]
Not working for me. Is there a solution?

**Comment by richardconrad** [comment]
Could someone please provide the equivalent solution for Windows?

**Comment by ptwobrussell** [comment]
@richardconrad @ejovi - See the comment at https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition/issues/243#issuecomment-70094461 - I'm having a hard time understanding how this has anything at all to do with the host operating system. It appears to me that perhaps the Vagrant box changed recently (or perhaps apt-get recently updated where it installs python) and the python binary isn't where Chef is expecting it to be. I think #243 should be a suitable workaround until I update the Chef recipe to take this into account.

**Comment by richardconrad** [comment]
I haven't tried this.  I'm about to; but I just wanted to say thank you very much for replying and trying to help.  It's much appreciated.
Cheers,
Richard
----Original message----
From : notifications@github.com
Date : 15/01/2015 - 14:46 (GMTST)
To : Mining-the-Social-Web-2nd-Edition@noreply.github.com
Cc : richardconrad@btinternet.com
Subject : Re: [Mining-the-Social-Web-2nd-Edition] Cant have Chef to successfully finish installing packages. (#245)
@richardconrad @ejovi - See the comment at #243 (comment) - I'm having a hard time understanding how this has anything at all to do with the host operating system. It appears to me that perhaps the Vagrant box changed recently (or perhaps apt-get recently updated where it installs python) and the python binary isn't where Chef is expecting it to be. I think #243 should be a suitable workaround until I update the Chef recipe to take this into account.

**Comment by richardconrad** [comment]
Hi Matthew,
But the problem I have is that I'm on Windows and these are Unix commands.  I do have cygwin installed but there's no 'sudo' there (there is, however, a 'su.exe'.  Should I try using that instead of sudo?).  I did see the error message indicating vagrant expected to find '\bin\python' and tried renaming my Python27 directory so that I now have a \bin\python' but that didn't work.  can you suggest anything, please?
Cheers,
Richard
----Original message----
From : notifications@github.com
Date : 15/01/2015 - 14:46 (GMTST)
To : Mining-the-Social-Web-2nd-Edition@noreply.github.com
Cc : richardconrad@btinternet.com
Subject : Re: [Mining-the-Social-Web-2nd-Edition] Cant have Chef to successfully finish installing packages. (#245)
@richardconrad @ejovi - See the comment at #243 (comment) - I'm having a hard time understanding how this has anything at all to do with the host operating system. It appears to me that perhaps the Vagrant box changed recently (or perhaps apt-get recently updated where it installs python) and the python binary isn't where Chef is expecting it to be. I think #243 should be a suitable workaround until I update the Chef recipe to take this into account.

**Comment by ptwobrussell** [comment]
Are you following along with the video from the quick start guide or taking
a different approach? Your host machine may be a Windows machine but your
guest machine (the VM running via Vagrant) is a Linux machine. "vagrant
ssh" from your host machine logs you into your guest (Linux) machine.

**Comment by PaulDepraz** [comment]
I changed the OS to ubuntu but still had to run `vangrant up` [chef never succesfully..] then `vgrant destroy` then `vagrant up` multiple times until it finally worked out. I had other vagrant projects that gave me the same issue and I figured it has to do with discrete problems in the repos network. Well thank all for the support and happy Mining! ;)
