### ISSUE TITLE
Vagrant up -- running but not connecting

### ISSUE THREAD

**Issue by nataliabueno** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#251]
Hi all, 

I'm using OS X Yosemite 10.10.1. Before upgrading to Yosemite, things were running smoothly with vagrant. Now, after re-installing VB and many other things, I can't seem to get vagrant to work properly. I installed vagrant, but whenever I do "vagrant up", I get the following:  

Bringing machine 'default' up with 'virtualbox' provider...

Then, I try going to http://localhost:8888 and I get an error. But, when I try "vagrant status", I get this:

Current machine states:

default                   running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.

Any help? Thanks!

**Comment by nataliabueno** [comment]
Oh, and my Virtualbox version is 4.3.18r96516 and my Vagrant version is 1.7.2.

**Comment by ptwobrussell** [comment]
If memory serves, you will have to reinstall the latest version of virtualbox because some stuff changed on the file system as part of your Yosemite upgrade

---Sent from Boxer | http://getboxer.com

On January 18, 2015 at 6:02:16 PM CST, Natalia Bueno <notifications@github.com> wrote:Hi all,   I'm using OS X Yosemite 10.10.1. Before upgrading to Yosemite, things were running smoothly with vagrant. Now, after re-installing VB and many other things, I can't seem to get vagrant to work properly. I installed vagrant, but whenever I do "vagrant up", I get the following:   Bringing machine 'default' up with 'virtualbox' provider...  Then, I try going to http://localhost:8888 and I get an error. But, when I try "vagrant status", I get this:  Current machine states:  default running (virtualbox)  The VM is running. To stop this VM, you can run vagrant halt  to shut it down forcefully, or you can run vagrant suspend  to simply suspend the virtual machine. In either case, to restart it again, simply run vagrant up .  Any help? Thanks!  —Reply to this email directly or view it on GitHub.

**Comment by nataliabueno** [comment]
Hi, I already re-installed it -- for some reason, it was uninstalled during my upgrade. Thanks for the quick feedback, though. Any other thoughts?

**Comment by PaulDepraz** [comment]
Hi, Have you tried running 'sudo netstat -tulpn ' ou 'sudo netstat -tulpn |
grep 8888' before running vagrant? Maybe there are port conflicts. Mine
versions are 4.3.10_Ubuntur93012 and 1.4.3. They are a little backdated but
using latest was giving me lots of random problems. I had to run 'vagrant
destroy' and 'vagrant up' multiple times until it finally ran chef
succesfully once and got the provisioning done right.

**Comment by PaulDepraz** [comment]
Maybe you could try running 'vagrant up --provison' to check if the
provisioning is ok.

**Comment by nataliabueno** [comment]
Hi Paul, thanks! I ran Vagrant up --provision and it gave me some clues that there were some port conflicts. After some reading some dismal comments about these problems, I decided to try a hammer solution: I uninstalled vagrant and re-installed it -- using a different version. It seems to work. Thanks!

**Comment by dan-king** [comment]
@nataliabueno, re " I uninstalled vagrant and re-installed it -- using a different version. It seems to work.". That's promising! What version of vagrant is working for you? (I'm having no success with vagrant 1.7.2, the latest version.)

**Comment by dan-king** [comment]
I finally got it to work by uninstalling vagrant 1.7.2 and installing 1.7.1 instead.

Yosemite 10.10.1
VirtualBox 4.3.20
Vagrant 1.7.1
Created links as described in #243
