### ISSUE TITLE
Issues with Example 3-7.  Standardizing common job titles 

### ISSUE THREAD

**Issue by DefStrike** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#269]
I've run into 1 problems with this example. 

The #comment at the top of the example: 
.##Place your "Outlook CSV" formatted file at: resources/ch03-linkedin/my_connections.csv

This location is on the vagrant virtual machine. Do I have to ssh or use my network somehow to place the csv file from my local computer there?

I would really appreciate any input. Thanks.

**Comment by ptwobrussell** [comment]
Hi - apologies for the delayed response. A brief response is below:

1 - In order to get the csv file onto your Vagrant VM, you would just put
it in the proper location on your host machine as referenced in the comment
and Vagrant will automatically synchronize it onto the VM guest so that
it's able to be accessed by the IPython Notebook kernel running on that VM.
See http://docs.vagrantup.com/v2/synced-folders/

2 - You say that "Because split() is being called, contact['Job
Title'].split('/') it seems always returns a list which means t is also a
list." but this isn't quite right. The result of a split() operation indeed
returns a list but then the variable "t" is your looping variable that
iterates over each item in the list. You can verify this by playing around
in an interpreter with some sample values in list comprehensions.

**Comment by DefStrike** [comment]
All sorted. Thank you!
